# ====== Git ======
project_git_url = ${project_git_url}
git_pull_branch = ${git_branch}
credentialsId = 20260102-credential

# ======= S3 =======
s3_upload_bucket = ${s3_bucket_name}


# ====== Y/N ======
BUILD_ENABLE_YN = Y
BUILD_REACT_YN = N
BUILD_GRADLE_YN = N
STATIC_UPLOAD_YN = N
DOCKER_IMAGE_YN = N
